# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

application:
  name: mintegration
  namespace: mintegration

image:
  repository: maxisses/mintegration
  tag: latest
  imagePullPolicy: Always
  containerPort: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  containerPort: 3000
  port: 80
  selector: mintegration-selector

ingress:
  enabled: true
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    host: mintegration-halle.de

  tls:
    - secretName: letsencrypt-prod
      hosts:
        - mintegration-halle.de

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}