apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: welearnpubliccloud
spec:
  template:
    metadata:
      annotations:
        # minimum --> knative heißt nicht zwangsläufig 0
        autoscaling.knative.dev/minScale: "10"
        # maximum an erlaubten pods
        autoscaling.knative.dev/maxScale: "30"
        # handle 10 requests auf einmal pro pod
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: maxisses/maxapp:latest
        livenessProbe:
          httpGet:
            path: /health
          initialDelaySeconds: 60
          periodSeconds: 60