apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
  selector:
    app: {{ .Values.service.selector }}